- name: Creating group
  group:
    name: group_a
    state: present
  become: true

- name: Create and add user to the group
  user:
    name: "{{item}}"
    password: "{{pass | password_hash('sha512')}}"
    group: group_a
    home: "/home/{{item}}"
    shell: '/bin/bash'
    state: present
  with_items:
    - user_a
  become: true

- name: Adding privileges to the users
  lineinfile:
    path: '/etc/sudoers'
    line: "{{item}}"
    regexp: "^{{item}}"
  with_items:
    - Cmnd_Alias PASSWD = /usr/bin/passwd
  become: true

- name: Adding privileges to the users
  lineinfile:
    path: '/etc/sudoers'
    line: "{{item}} ALL=(ALL) NOPASSWD: PASSWD"
    regexp: "^{{item}}"
  with_items:
    - user_a
  become: true
